### ISSUE TITLE
Create a position data structure

### ISSUE THREAD

**Issue by zjg95** [zjg95/GSA#47]

**Comment by abcapindo** [comment]
Should this be like an array with the user entering position options or are we giving them set position options?

**Comment by zjg95** [comment]
We will create an object of type "position." It will likely have a name (string) and maybe a competency level (int). Each employee can then have a list of positions that they are qualified to work.

**Comment by abcapindo** [comment]
Okay i can do that right now unless you guys have already done that

**Comment by zjg95** [comment]
Nope! Haven't touched it. Otherwise I would have commented on the issue.

**Comment by abcapindo** [comment]
kk sounds good
